### ISSUE TITLE
Automated linking

### ISSUE THREAD

**Issue by DaKaZ** [rhdeck/react-native-setdevteam#2]
Unlike the other ios config tools, `react-native-setdevteam` does not auto-link.  For example, after I run 
```
react-native setdevteam XYZ123
```
I see the iosDevTeam persisted in ~/.rninfo.  However, if I clean my env like:
```
rm -rf ios
react-native eject
react-native link
```
the dev team is not set until I run `react-native setdevteam` again.  

I thinking it would make sense to automatically set the dev team IF the package,json had `iosDevTeam` in it.  Can you also tell me more about the logic behind using `~/.rninfo`?  Is that just so multiple apps can draw from a common config?

**Comment by rhdeck** [comment]
Fixed in 1.3. Now contains `react-native link` hook to automatically update the pbxproj file(s) with the value of `xcodeDevTeam` in `package.json`
